FROM node:12.18-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
#COPY ["package.json", "yarn.lock*", "./"]
COPY ./build .
RUN yarn global add serve
#RUN yarn install --production --non-interactive 
#&& mv node_modules ../
EXPOSE 3000
CMD ["serve", ".", "-l", "3000"]