stages:    
  - Build
   
image: docker/compose
   
build:
  stage: Build
  services:
    - docker:19.03.12-dind
  
  before_script:
    - docker info
    - apk add --update nodejs npm
    - npm install -g yarn

  script:
    - cd ./client
    - yarn install
    - yarn run build
    - cd ..
    - docker-compose -f "docker-compose.yml" up -d --build 